on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Hardhat
      run: npm install -g hardhat
    - name: Compile contract
      run: hardhat compile
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Hardhat
      run: npm install -g hardhat
    - name: Test contract
      run: hardhat test
  review:
    if: ${{success()}}
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Deployment review"
        title: "Deployment review for ${{github.sha}}"
        body: "Please review the deployment for ${{github.sha}}"
        labels: "deployment, review"
        reviewers: "team-member-1, team-member-2"
        assignees: "team-member-1, team-member-2"
  deploy:
    if: ${{success()}}
    needs: review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Hardhat
      run: npm install -g hardhat
    - name: Deploy contract
      run: hardhat deploy --network volta
  notify:
    if: ${{success()}}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify team
