name: Deploy Upgrade

on:
  push:
    branches:
      - main
    paths:
      - 'deployV2/**'
    types:
      - added
      - modified

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy Contract Upgrade
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install dependencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: npx hardhat run deployV2/deployV2.js --network volta