name: Deploy Smart Contract

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Hardhat
      run: yarn add hardhat

    - name: Compile and deploy the smart contract using Hardhat
      run: |
        
        yarn run hardhat compile
        yarn run hardhat deploy

    - name: Notify of deployment success
      run: |
        # Your notification script here (e.g. sending an email, Slack message, etc.)
