name: Deploy Smart Contract

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16
  

jobs:
  Smart_Contract_Automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Hardhat
      run: yarn add hardhat
      
    - name: Install dependencies
      run: npm install

    - name: Compile and deploy the smart contract using Hardhat
      run: |
        yarn run hardhat compile
        
    - name: Test
      run: |
        yarn run hardhat test
        
    - name: Deploy 
      run: |
        yarn hardhat run --network Volta ./scripts/deploy.js

       
     

