name: Deploy Smart Contract

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16
  

jobs:
  Smart_Contract_Automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Hardhat
      run: yarn add hardhat
      
    - name: Install dependencies
      run: npm install

    - name: Compile 
      run: |
        yarn run hardhat compile
        
    - name: Test
      run: |
        yarn run hardhat test
        
    - name: Select deployment network
      id: network_prompt
      uses: actions/bin/read-input@v2
      with:
        name: network
        message: "Please select the network to deploy to (Volta or EWC)"
        default: Volta
          
        
    - name: Deploy to selected network
      run: |
        network=${{ steps.network_prompt.outputs.network }}
        echo "Deploying to network $network"
        yarn hardhat run --network $network ./scripts/deploy.js

       
     

