name: Deploy Smart Contract

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install Hardhat dependencies
      run: |
       npm install --save-dev hardhat

    - name: Compile and deploy the smart contract using Hardhat
      run: |
        npm install -g hardhat
        hardhat compile
        hardhat deploy

