name: Proxy & Proxy Admin Contract Deployment

on:
  push:
    branches:
      - Transparent 
    paths:
      - 'deploy_Proxy/**'

    
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node:version: current
          
      - name: Install depndencies 
        run: npm ci
        
      - name: Installing hardhat
        run: npm install -g hardhat
        
      - name: Installing OpenZepplin Contract
        run: npm install @openzeppelin/contracts
        
      - name: Compile contract
        run: npx hardhat compile

      - name: Test contract
        run: npx hardhat test

      - name: Deploy contract
        run: npx hardhat run deploy_Proxy/deploy_Proxy_proxyAdmin.js --network volta
